services:
  redis:
    image: redis:latest
    container_name: better-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: better-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

