# Generated by Django 5.2.1 on 2025-09-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDay',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('day', models.DateField()),
                ('score', models.PositiveIntegerField(null=True)),
                ('max_score', models.PositiveIntegerField(null=True)),
            ],
            bases=('better.basemodel',),
        ),
        migrations.CreateModel(
            name='TargetCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(null=True)),
                ('max_score', models.PositiveIntegerField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='better.scoreday')),
            ],
            bases=('better.basemodel',),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
                ('importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='better.importance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='better.targetcategory')),
            ],
            bases=('better.basemodel',),
        ),
    ]
