# Generated by Django 5.2.1 on 2025-09-19 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, unique=True)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreDay',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('day', models.DateField(unique=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-day'],
            },
            bases=('better.basemodel',),
        ),
        migrations.CreateModel(
            name='TargetCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='better.scoreday')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('day', 'name')},
            },
            bases=('better.basemodel',),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
                ('importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='better.importance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='better.targetcategory')),
            ],
            options={
                'ordering': ['-importance__score', 'name'],
            },
            bases=('better.basemodel',),
        ),
    ]
