# Generated by Django 5.2.1 on 2025-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreday',
            name='sleep_time',
            field=models.DateTimeField(blank=True, help_text='Time when you went to sleep', null=True),
        ),
        migrations.AddField(
            model_name='scoreday',
            name='wake_time',
            field=models.DateTimeField(blank=True, help_text='Time when you woke up', null=True),
        ),
    ]
