# Generated by Django 5.2.1 on 2025-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0002_scoreday_sleep_time_scoreday_wake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this category represents'),
        ),
    ]
